function sayHello()
{
   alert("dont press ok!");
   alert("hehehehehehe i warned you not to");
            alert("NOW ILL MAKE YOU SUFFER!!!MWAHAHAHAHAHA!!!");
         alert("now lets recite the alphabet!!!");
         alert("A");
        alert("B");
      alert("C");
    alert("D");
    alert("E");
    alert("F");
} alert("G");
 alert("H");
  alert("I");
  alert("J");
  alert("K");
  alert("L");
  alert("M");
  alert("N");
  alert("O");
  alert("P");
  alert("Q");
  alert("R");
  alert("S");
  alert("T");
  alert("U");
  alert("V");
  alert("W");
  alert("X");
  alert("Y");
  alert("Z");
  alert("That was fun !!!");
  alert("what should we do next?");
  alert("OOOOH I know lets count the numbers!!!!!");
  alert("1");
  alert("2");
  alert("3");
  alert("4");
  alert("5");
  alert("6");
  alert("7");
  alert("8");
  alert("9");
  alert("10");
  alert("11");
  alert("12");
  alert("13");
  alert("14");
  alert("15");
 alert("16");
  alert("17");
  alert("18");
  alert("19");
  alert("20");
 alert("21");
 alert("22");
  alert("23");
  alert("24");
  alert("25");
  alert("26");
  alert("27");
  alert("28");
  alert("29");
  alert("30");
   alert("31");
   alert("32");
   alert("33");
   alert("34");
   alert("35");
   alert("36");
   alert("37");
   alert("38");
   alert("39");
   alert("40");
   alert("41");
   alert("42");
   alert("43");
   alert("44");
   alert("45");
   alert("46");
   alert("47");
   alert("48");
   alert("49");
   alert("50");
   alert("51");
   alert("That was fun!!!!!");
   alert("I'm getting bored");
   alert("Ill let you go now");
   alert("ok bye");
   alert("i said bye");
   alert("you can go now");
   alert("I SAID YOU CAN GO NOW!!!!!!");
   alert("finally hes gone");
  alert("wait are you still here??"); 
   alert("Get out!!!!");
   alert("OH MY GOD GET OUT!!!!!!");
   alert("WHY ARE YOU STILL HERE!?!?!?!?!?!?!?!?!?");
   alert("Fine..Fine...Finneeee");
   alert("ill let you go");
   alert("JK IM NEVER GONNA LET YOU GO MAYBE ILL EVEN DO THIS TO YOU FOREVER");
   alert("OK OK OK IM JUST KIDDING");
   alert("HAHAHAHAHAHA YOU THOUGHT I WAS GONNA LET YOU GO!?!");
   alert("Ok Ok Ok im just kidding or am i???");
   alert("Ok ill let you go now  bye bye");
   alert("MWHAHAHAHAHAHAHAHAHAHAHAHAHA");
  
  
sayHello();
 